PLAY_STATE = 0
EDIT_STATE = 1

PLAYER_MOVEMENT_SPEED = 10

PPP = 3 # PIXELS PER POSITION
PPT = 16 # PIXELS PER TILE

TILE_WIDTH = PPT * PPP
TILE_HEIGHT = PPT * PPP

WORLD_WIDTH = 16
WORLD_HEIGHT = 12


MARGIN = TILE_WIDTH

SCREEN_WIDTH = WORLD_WIDTH * TILE_WIDTH + 2*MARGIN
SCREEN_HEIGHT = WORLD_HEIGHT * TILE_HEIGHT + 2*MARGIN


MASTER_VOLUME = 100

BACKGROUND_COLOUR = (33, 33, 35)
